name: Sync waw default project to waw-default

on:
  push:
    paths:
      - 'server/**' # Trigger only on changes in the server folder

jobs:
  sync-waw:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3

    - name: Set up SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Sync waw default folder to waw-default
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git clone git@github.com:WebArtWork/waw-default.git waw-default
        rm -rf waw-default/*
        cp -r server/* waw-default/
        cd waw-default
        git add .
        git commit -m "Update files from source repository" || echo "No changes to commit"
        git push --force

    - name: Clean up SSH
      run: |
        rm -f ~/.ssh/id_rsa
        rm -f ~/.ssh/known_hosts
