name: Sync wjst default project to wjst-default

on:
  push:
    paths:
      - 'template/**' # Trigger only on changes in the template folder

jobs:
  sync-wjst:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3

    - name: Set up SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Sync wjst default folder to wjst-default
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git clone git@github.com:WebArtWork/wjst-default.git wjst-default
        rm -rf wjst-default/*
        cp -r client/* wjst-default/
        cd wjst-default
        echo "wjst-default.webart.work" > CNAME
        git add .
        git commit -m "Update files from source repository" || echo "No changes to commit"
        git push --force

    - name: Clean up SSH
      run: |
        rm -f ~/.ssh/id_rsa
        rm -f ~/.ssh/known_hosts
